In [19]:

import os
import requests
import pandas as pd
from dotenv import load_dotenv

In [20]:
# Load GitHub token from .env

load_dotenv()

GITHUB_TOKEN = os.getenv("GITHUB_TOKEN")

if not GITHUB_TOKEN:
    raise ValueError(
        "GITHUB_TOKEN not found. Check your .env file."
    )

In [21]:
# Configure GitHub repository

GITHUB_OWNER = "jabedulislam83"
GITHUB_REPO = "retail-intelligence-platform"
GITHUB_BRANCH = "main"

In [22]:
# Configure GitHub API authentication headers

HEADERS = {
    "Authorization": f"Bearer {GITHUB_TOKEN}",
    "Accept": "application/vnd.github+json",
    "X-GitHub-Api-Version": "2022-11-28"
}

In [23]:
# Define GitHub CSV file paths

FILE_PATHS = {
    "sales": "data/sales.csv",
    "customers": "data/customers.csv",
    "products": "data/products.csv",
    "inventory": "data/inventory.csv"
}

In [24]:
# Create function to load CSV files from GitHub REST API

def load_github_csv(owner, repo, file_path, branch="main"):

    api_url = (
        f"https://api.github.com/repos/"
        f"{owner}/{repo}/contents/{file_path}"
        f"?ref={branch}"
    )

    response = requests.get(
        api_url,
        headers=HEADERS,
        timeout=30
    )

    response.raise_for_status()

    data = response.json()

    if data.get("type") != "file":
        raise ValueError(
            f"GitHub path is not a file: {file_path}"
        )

    download_url = data.get("download_url")

    if not download_url:
        raise ValueError(
            f"No download URL found for: {file_path}"
        )

    raw_response = requests.get(
        download_url,
        timeout=60
    )

    raw_response.raise_for_status()

    df = pd.read_csv(
        raw_response.url
    )

    return df

In [30]:
# Extract sales dataset from GitHub

sales_df = load_github_csv(
    GITHUB_OWNER,
    GITHUB_REPO,
    FILE_PATHS["sales"],
    GITHUB_BRANCH
)

print("Sales dataset extracted successfully.")
print("Shape:", sales_df.shape)

Sales dataset extracted successfully.
Shape: (51545, 12)

In [29]:
sales_df.head()

,order_id,order_date,ship_date,customer_id,product_id,sales,quantity,discount,profit,shipping_cost,ship_mode,order_priority
0,NI-2011-4760,12/21/2011,12/25/2011,LB-67951,TEC-PAN-10001593,15,1,0.7,-28.23,0.980,Standard Class,Medium
1,ES-2012-4572658,7/14/2012,7/19/2012,CJ-118752,OFF-EN-10001991,5,1,0.5,-4.50,0.360,Standard Class,Medium
2,MX-2014-108602,11/4/2014,11/11/2014,PM-191353,OFF-FA-10004410,21,3,0.0,3.12,0.614,Standard Class,Medium
3,GH-2014-2090,5/16/2014,5/23/2014,MS-78301,OFF-SAN-10001128,11,1,0.0,2.61,0.990,Standard Class,Medium
4,ES-2013-5731775,12/31/2013,1/7/2014,GM-144552,OFF-FA-10004997,71,5,0.0,26.10,6.690,Standard Class,Low

In [31]:
# Extract customers dataset from GitHub

customers_df = load_github_csv(
    GITHUB_OWNER,
    GITHUB_REPO,
    FILE_PATHS["customers"],
    GITHUB_BRANCH
)

print("Customers dataset extracted successfully.")
print("Shape:", customers_df.shape)

Customers dataset extracted successfully.
Shape: (25083, 8)

In [32]:
customers_df.head()

,customer_id,customer_name,segment,city,state,country,region,market
0,BP-112903,Beth Paige,Consumer,Santo Domingo,Santo Domingo,Dominican Republic,Caribbean,LATAM
1,TB-112803,Toby Braunhardt,Consumer,Khorramshahr,Khuzestan,Iran,EMEA,EMEA
2,OT-187301,Olvera Toch,Consumer,Raipur,Chhattisgarh,India,Central Asia,APAC
3,MM-172601,Magdelene Morse,Consumer,Ichalkaranji,Maharashtra,India,Central Asia,APAC
4,FH-143654,Fred Hopkins,Corporate,New York City,New York,United States,East,US

In [33]:
# Extract products dataset from GitHub

products_df = load_github_csv(
    GITHUB_OWNER,
    GITHUB_REPO,
    FILE_PATHS["products"],
    GITHUB_BRANCH
)

print("Products dataset extracted successfully.")
print("Shape:", products_df.shape)

Products dataset extracted successfully.
Shape: (10821, 4)

In [34]:
products_df.head()

,product_id,product_name,category,sub_category
0,TEC-AC-10003447,Micropad Numeric Keypads,Technology,Accessories
1,OFF-LA-10001028,"Hon Removable Labels, Adjustable",Office Supplies,Labels
2,OFF-LA-10001924,"Hon Round Labels, Adjustable",Office Supplies,Labels
3,OFF-AP-10002361,"Hoover Microwave, Red",Office Supplies,Appliances
4,FUR-CH-10003061,"Global Leather Task Chair, Black",Furniture,Chairs

In [35]:
# Extract inventory dataset from GitHub

inventory_df = load_github_csv(
    GITHUB_OWNER,
    GITHUB_REPO,
    FILE_PATHS["inventory"],
    GITHUB_BRANCH
)

print("Inventory dataset extracted successfully.")
print("Shape:", inventory_df.shape)

Inventory dataset extracted successfully.
Shape: (10800, 6)

In [36]:
inventory_df.head()

,product_id,warehouse,stock_quantity,reorder_level,stock_status,last_updated
0,OFF-KLE-10000527,Singapore Warehouse,256.0,51.0,In Stock,2026-07-20
1,FUR-TA-10003690,Rotterdam Warehouse,70.0,14.0,In Stock,NaN
2,OFF-ELI-10001351,Singapore Warehouse,445.0,89.0,In Stock,2026-07-20
3,FUR-CH-10002780,Rotterdam Warehouse,NaN,12.0,In Stock,2026-07-20
4,TEC-PH-10001536,Chicago Warehouse,104.0,20.0,In Stock,2026-07-20